name: PR checks
on: [pull_request]

env:
  CI: true

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      # Reset the README.md after generate, else Prettier will fail
      - name: Run lint
        run: |
          yarn install
          yarn compas generate application --skip-lint
          git checkout -- README.md
          yarn compas lint

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Run tests
        run: |
          yarn install
          yarn compas generate application --skip-lint
          yarn compas docker up
          yarn compas migrate
          yarn compas test
