name: PR checks
on: [pull_request]

env:
  CI: true

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # Reset the README.md after generate, else Prettier will fail
      - name: Run lint
        run: |
          npm install
          npx compas generate application --skip-lint
          git checkout -- README.md
          npx compas lint

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Run tests
        run: |
          npm install
          npx compas generate application --skip-lint
          npx compas docker up
          npx compas migrate
          npx compas test
